### ISSUE TITLE
Exception: "The specified module could not be found"

### ISSUE THREAD

**Issue by alexanderkozlenko** [Microsoft/xunit-performance#255]
```
System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found

   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.LoadKernelTraceControl()
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.Merge(String[] inputETLFileNames, String outputETLFileName, EVENT_TRACE_MERGE_EXTENDED_DATA flags)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.MergeInPlace(String etlFileName, TextWriter log)
   at Microsoft.Xunit.Performance.Api.ETWProfiler.Record(XUnitPerformanceSessionData xUnitPerformanceSessionData, XUnitPerformanceMetricData xUnitPerformanceMetricData, Action action)
   at Microsoft.Xunit.Performance.Api.XunitPerformanceHarness.RunBenchmarks(String assemblyFileName)
   at ConsoleApp1.Program.Main(String[] args) in D:\Workspace\projects\ConsoleApp1\ConsoleApp1\Program.cs:line 13
```

A self containing harness + benchmark: netcoreapp2.0 / .NET Core 2.0.5

```
xunit.performance.api 1.0.0-beta-build0015
Microsoft.Diagnostics.Tracing.TraceEvent 2.0.2
```
[ConsoleApp1.zip](https://github.com/Microsoft/xunit-performance/files/1627640/ConsoleApp1.zip)

**Comment by jorive** [comment]
@alexanderkozlenko You are not using the right version of the Tracing library. You should be using version 1.0.3-alpha-experimental.

**Comment by alexanderkozlenko** [comment]
It works as expected with version `1.0.3-alpha-experimental`, thanks!

**Comment by jorive** [comment]
@alexanderkozlenko sorry for the inconvenience.
