### ISSUE TITLE
Unable to run benchmarks from Test Explorer

### ISSUE THREAD

**Issue by alexanderkozlenko** [Microsoft/xunit-performance#256]
```
[01/13/2018 01:34:03 Informational] ------ Load Playlist started ------
[01/13/2018 01:34:03 Informational] ========== Load Playlist finished (0:00:00.0044991) ==========
[01/13/2018 01:34:03 Informational] ------ Discover test started ------
[01/13/2018 01:34:03 Error] C:\Users\user\AppData\Local\Temp\VisualStudioTestExplorerExtensions\2.3.1/build/netcoreapp1.0/xunit.runner.visualstudio.dotnetcore.testadapter.dll
[01/13/2018 01:34:05 Informational] [xUnit.net 00:00:00.3871183]   Discovering: XUnitTestProject1
[01/13/2018 01:34:05 Informational] [xUnit.net 00:00:00.4883907]   Discovered:  XUnitTestProject1
[01/13/2018 01:34:09 Informational] ========== Discover test finished: 1 found (0:00:05.4915221) ==========
[01/13/2018 01:35:05 Informational] ------ Discover test started ------
[01/13/2018 01:35:06 Informational] [xUnit.net 00:00:00.4280562]   Discovering: XUnitTestProject1
[01/13/2018 01:35:06 Informational] [xUnit.net 00:00:00.5758118]   Discovered:  XUnitTestProject1
[01/13/2018 01:35:06 Informational] ========== Discover test finished: 1 found (0:00:01.2182892) ==========
[01/13/2018 01:35:06 Informational] ------ Run test started ------
[01/13/2018 01:35:08 Warning] [xUnit.net 00:00:00.4258711] XUnitTestProject1: Catastrophic error during deserialization: System.ArgumentException: Could not load type 'Microsoft.Xunit.Performance.BenchmarkTestCase, xunit.performance.{Platform}' from serialization value 'Microsoft.Xunit.Performance.BenchmarkTestCase, xunit.performance.{Platform}:VGVzdE1ldGhvZDpYdW5pdC5TZGsuVGVzdE1ldGhvZCwgeHVuaXQuZXhlY3V0aW9uLntQbGF0Zm9ybX06VFdWMGFHOWtUbUZ0WlRwVGVYTjBaVzB1VTNSeWFXNW5PbFpIVm5wa1JVcHNZbTFPYjJKWFJubGhkejA5Q2xSbGMzUkRiR0Z6Y3pwWWRXNXBkQzVUWkdzdVZHVnpkRU5zWVhOekxDQjRkVzVwZEM1bGVHVmpkWFJwYjI0dWUxQnNZWFJtYjNKdGZUcFdSMVo2WkVWT2RtSkhlR3haTTFKd1lqSTBObGRJVm5WaFdGRjFWVEpTY2t4c1VteGpNMUpFWWpKNGMxcFhUakJoVnpsMVRFTkNOR1JYTlhCa1F6VnNaVWRXYW1SWVVuQmlNalIxWlRGQ2MxbFlVbTFpTTBwMFpsUndVMUl5ZURaWk1HUTBZVWRXVms1WGFHbFdNVlV5VmxST2MyVnRVa2hXYmxKTllrVTBkMWt5TVhOa1ZuQTJZMFprVTAxV2J6SlhhMVpQVVRKR2RGTlliR3hUUlRWb1ZtcEJNR1F4YkZkWmVsWnJWbGQ0U1ZZeU5XRmhiVVpXVTJ4d1YySkhUWGhaTUdSVFVqRldkR1ZIY0U1TlZYQlRWMVJKZDA1WFRsZGpSbWhWWVd0S1QxWlljRmRXTVd4MFRWaE9UbEpzY0VsV2JUVjNZVEZLUmxaVWJFUmlSa3B6V1hwT1UxRnRUWHBVYlhocFZqQndlbHBXVW5kWFYxSllUbGhDYTFGNlZsVlhhMlI2WkZaYVNGWnVjR3RTVlZvMldYcEtWMlJHYkhSbFJGWk5VVEJKTUZwR1l6RmpSMUpFVGxkNGJGSXhXbkZhUm1oVFkwZEplVTVJVm14TlZVcDZWMVpvVTJKWFNYcFRibEp0VmtoQ1UxWXdWVEZPYkdSeldUTm9hRll3Y0VwWmExcEhWMnhrUjFOdVdsVk5ibWhRVkd4a1RtVnNWblJsUjJ4V1pXeGFWbGRyVm05VE1rNUlVMjVTV21Wc2NGaFVWVnAzVjBad1IxcEZaRmhXYkZwNlZtMHhSMWRHU2xWVmFrNVhZa1phZGxWNlNsTmtSa3AxVld4a2FWZEZTbmxXVjNSWFZqQXhWMXBJU21GU1JrcHhXa1JPUTFKV2JIRlRWRVpwVmpCYVdWZHJWbXRoUmxsNllVaE9WMUo2UmtoYVJWcDNWbGRPUjFWdGVGaFNWRkl6VmpKNGFtUXlVbGRWV0d4VVltdGFhRlpxUVRCa01VVjVaVWRHYVZJd05URldSelZEWVZVeGNWVlVTbGRXUlRWNldsY3hVMU5HV25WVmF6RnBVbFJTTTFkVVNYaGpNbEpYWTBSYWFsSlVWbGRhVjNoS1pXeGFSbHBJWkZKaVZrcFhWRlpXUzFWV1drVlJWR3hFWWtaYU1WbFdhRWROVm5CV1lrVldVR0pGTkRGWmVrNVRZa2RLVkU1V1VtdFRSWEIzV1cweGFrNXNaRlZUYTNCUFZsUnNTVlp0TVhOWlZsbDRWbXBDV0ZaNlJrZGFSRUV4VWtVeFJWRnJPVmROUjNRMFZrVmFhMU15U2xkalJXaFVWMFpLYUZsWGVGZE5NV1J6VldzNWFGSnVRbFpXVm1odlZERmFTRmt6Y0VSaE1VcHpWMVJLTkdGSFRuUlNha0pvVm5wc01WVldhRTlsYkhCWVRWZHNhVk5IZUZCWFZtTjRZa1U1YzFScVZtcE5NVXB6V1d4Tk1WVkdiSFJqUjNoYVRURkdURlZyWkZkaGJVcElVbTVzV2xkR1NuZFpha2t4VmxkV1dWRnRlRlZpVlZvd1YyeFNkMVpIVmxsVWFrSmhWbnBDTVZaRVNrdGpWbkJZVkdwQlMxRXllR2hqTTA1Q1l6Tk9iR0pYU25ObFZUVm9ZbGRWTmxVemJIcGtSMVowVEd4T01HTnRiSFZhZW5CWVVteGFNVmxXYUZOV1ZuQlpWR3BDVmxORmNESlpWekZYWVcxU1JWSllUa3BTYkhCeldUSTFUMk5IU1hsT1JHeE9WWHBTTTFSSGNFSmtWVEZFWkRKa1VrMHhXbnBhUldoWFpWWndWVTFZVm1GWFJsbDNXVEl4UjJNd2VFUlJiRVpyVmpCd2VsbFdaRTlVUm5CWllrWldhVTF1VW5OWmJXOTRaRmRTV0dWSVRVdFJNbmhvWXpOT1ZXVllRbXhVYlVaMFdsUndWR1ZZVGpCYVZ6QjFWVE5TZVdGWE5XNVBiR1JIVm01V2FGZEdTbFpYYkdoUFRVWldTVk51V21oaVZscHhXa1ZTUm1SV1dsaE9XRUpyVW14S2MxbDZUbEpsUVQwOQpUZXN0TWV0aG9kQXJndW1lbnRzOlN5c3RlbS5PYmplY3QKRGVmYXVsdE1ldGhvZERpc3BsYXk6U3lzdGVtLlN0cmluZzpRMnhoYzNOQmJtUk5aWFJvYjJRPQpEaXNjb3ZlckFyZ3VtZW50czpTeXN0ZW0uQm9vbGVhbjpUcnVl'
Parameter name: serializedValue
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 38
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 59
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 522
[01/13/2018 01:35:08 Informational] [xUnit.net 00:00:00.4583680]   Starting:    XUnitTestProject1
[01/13/2018 01:35:08 Informational] [xUnit.net 00:00:00.5032304]   Finished:    XUnitTestProject1
[01/13/2018 01:35:08 Informational] ========== Run test finished: 0 run (0:00:01.3792886) ==========
```
xUnit project: netcoreapp2.0 / .NET Core 2.0.5
```
VisualStudio.15.Release/15.5.3+27130.2020

Microsoft.Diagnostics.Tracing.TraceEvent 1.0.3-alpha-experimental
xunit 2.3.1
xunit.performance.api 1.0.0-beta-build0015
xunit.runner.visualstudio 2.3.1
```
[XUnitTestProject1.zip](https://github.com/Microsoft/xunit-performance/files/1627850/XUnitTestProject1.zip)

**Comment by jorive** [comment]
@alexanderkozlenko Could you please try adding the line below to the .cs file, and try again?
```csharp
[assembly: OptimizeForBenchmarks]
```

**Comment by joshuaduffy** [comment]
Microsoft Visual Studio Enterprise 2017 
Version 15.5.4
VisualStudio.15.Release/15.5.4+27130.2024
Microsoft .NET Framework
Version 4.7.02046

Hey,

I am having the same issue as above on `1.0.0-beta-build0016`

I'm using `xunit` `v2.3.0` (our company has not upgraded but I did a quick check on 2.3.1 and I get the same issue) and  `xunit.runner.visualstudio` `v2.3.1`

Did you manage to work out what was causing the issue?

**Comment by joshuaduffy** [comment]
Better stacktrace..

    [22/01/2018 16:00:30 Informational] ------ Run test started ------
    [22/01/2018 16:00:30 Error] [xUnit.net 00:00:00.3537754] Emis.Benchmarks: Test case Hello(patientId: 
    10877) failed to deserialize: System.ArgumentException: Could not load type 
    'Microsoft.Xunit.Performance.BenchmarkTestCase, xunit.performance.{Platform}' from serialization     value 'Microsoft.Xunit.Performance.BenchmarkTestCase, xunit.performance.    {Platform}:VGVzdE1ldGhvZDpYdW5pdC5TZGsuVGVzdE1ldGhvZCwgeHVuaXQuZXhlY3V0aW9uLntQbGF0Zm9ybX06VFdWMGFHOWtUbUZ0WlRwVGVYTjBaVzB1VTNSeWFXNW5PbEl5VmpCVlIwWXdZVmRXZFdSR1NteFpNamw1V2tWS2JHSnRUbTlpVjBaNVlYYzlQUXBVWlhOMFEyeGhjM002V0hWdWFYUXVVMlJyTGxSbGMzUkRiR0Z6Y3l3Z2VIVnVhWFF1WlhobFkzVjBhVzl1TG50UWJHRjBabTl5YlgwNlZrZFdlbVJGVG5aaVIzaHNXVE5TY0dJeU5EWlhTRloxWVZoUmRWVXlVbkpNYkZKc1l6TlNSR0l5ZUhOYVYwNHdZVmM1ZFV4RFFqUmtWelZ3WkVNMWJHVkhWbXBrV0ZKd1lqSTBkV1V4UW5OWldGSnRZak5LZEdaVWNGTlNNbmcyV1RCa05HRkhWbFpPVjJocFZqRlZNbFpVVG5ObGJWSklWbTVTVFdKRk5IZFpNakZ6WkZad05tTkdaRk5OVm04eVYydFdUMUV5Um5SVFdHeHNVMFUxYUZacVFUQmtNV3hYV1hwV2ExWlhlRWxXTWpWaFlXMUdWbE5yWkZwaVIxSjZXbGQwTkdOc1RuUmxSMnhwVmxSV01sZFhlR3RTTWxaWVVsaHdWVmRHV2xOWmJGcGhUVlprVlZOdE9XdFNiWGhhVlRJMVMyRnRWbFZXYTJ4WVlrZG9WRlpXV25OWFZsWjFVVzFHVjJWc1ZqTldiR040VmpKR2RGTlljRlJpV0U1TVZtdGtWMlZ0VWtaU2JuQnFUV3hhTUZkWE1UUk9WVGx6WVVSR2FXSlhkM2RVUjNoUFlUSkdOVTVXVm1GWFJUUjNWVlpvVDJWc2NGaE5WMnhwVTBkMGVsTlZhRzlOVjBwMFlrUkNUV0pXV1RCWGJHUlBUVmRTU0dKSVdtbGhWRlV6VmxWa05HRkhVa2hYYmxwcVlsUkZOVlF5ZUVkWFZsSjFZMGRHVjJWclduZFhWM1J2WXpGV1YySkdiRlppVkd4UldXdFZNRTFXYkRaVWJFNXBVakJ3VlZSc1dsTmhNVTVHWTBoa1dtSlVSbkZVYlhoWFYxZE9TVnBHY0U1V2JGa3hWa1JHVTFJeVJuUlRiRnBQVjBVMVdWVnNXbUZYUmxwSVpVVTVWMDFXU2xsWGExcHJWRzFLUjJOSVpGZE5SbHBYV2xWa1IxTkdTbk5oUlRsWFRVUldWVlp0ZUZOU01VMTRWMnhzYVZKVk5WbFZiVFZEVjFaVmVVMVZPVmROVjFKSVZUSTFhMWR0UlhsVmJuQlZWbGRTU0ZZd1dtRmtWMDVIWWtaT1YySkhPVE5XTVZwaFlqRlNkRlZzWkZOaWJFcFlXVzE0WVZsV1VsaE5WemxPVW0xU1dGbFZWakJoYlVwV1RWUlNZVlpYVW5wWlZWcGhUbXhhZEdOR1dtbFNNRFF3VjFSQ2ExUXdOVlpPVmxwVllsVmFXRnBYZUdGbFJtUlhWbTF3YkZJd1drbFdSelZUWVRGT1NWRnJOVnBXUlZwTVZrZDRZVkpzU2xWaVJrWldWMFZLUmxkWGNFcE5WMHBZVW14b1lWSlhVbTlXYWs1dll6RmFTRTFWWkd0U2JrSldXVEJhVTJKR1pFWk9TR1JZWWtkT00xcEdXbFpsYkZaMVlrZG9WMlZzV2pGV1JFbzBVakExZEZScmFGVmlSbkJQV1ZjeE1FNUdaRlZUV0doVlRXdHdTRmxWVm1GV01rWTJWbXhXVjJKWVRqUlpiWGhoWTFaT2MxcEhhRmRpVjJoSVZrWmFhMkl5UmtkWGFscFhZbGhDVjFscldsZE9SbFY1WlVaa1QxWnJXbnBaVldSSFZqQXhTVkZ1UmxkaVdHaDJWbFJLVDFOR1RuSmhSMnhUVWxWd2RsWnRjRWRaVlRWeldrVmFWMkpIVW5KVmFrSmhWMnhhUjJGR1pGWmlWWEJZVmpKd1IxZEdXa1pqU0ZwaFVsWndlbFl4V2s5a1ZrNTBZMFUxV0ZJeWFETldNVnBoWVdzeFYyRXphRlJpUjJoUFZqQldTMk5XY0ZkVmJHUlRVbTFTZWxkWWNFZGhSMHBXVjJ0c1ZWWnRVblpaVnpGTFYxWldjVmRzVmxObGExcFZWMWh3UzFNeFNrWk9WbWhxVWpKNFQxbFhlR0ZOUm1SWFYyMTBhR0pGU2xOWk1GcHJXVlprUm1ORVdscFdiVTB4V2taVk5XTXhVbkZXYlhCT1RWVndlbGRYZUU1TlZscElWV3RzVkdKclNuQlpiR1JPVFd4YVIxZHJOVTVTTVVZeldsVm9SMVZzWkVkWGF6bFdWbXhHTTFReFJuZFdiVXAwWWtob2ExWXhXa3RWYTFKM1ZrZFdXVlJxUW1GV2VrSXhWbFJPVTJWWFJsaE9WelZRWVhwc1NWVnNVbGRaVmxwSVl6TmtWVlpXU2s5YVJWcHpZMVprV1dGRk9WWmxhMFl6VmtSQ1UyRXlSWGRsUmxab1RUSm9ZVnBYYzNoTlJsSnlXa1Z3VGsxRWJFWlZiVEI0V1ZkS1ZsWnFUbGhpUmtwMVZHeEdkMUpXY0ZoVWJrNWFWMFZ3YjFwRlpITmtiVXB5VW01d2FrMXNXakJYVnpFMFRsWlNkRkp1VW1GV1NFSlZXbFpvVDAxR2NGaE5TRlpWVFd0d2VGZHNaRTlOUlU1eVZXMTRXazF1YUc5Wk1qRkhUVWRHV0U5WVZsZFRSM2d6VjJ4Vk1XRkhTbGhXVkZwV1RUSjRObHBGWkZka1JYaHlUMWRzYUdKV1duRmFSVVU1VUZGd1JHSkhSbnBqTUVaNll6SldkRmx0ZURWVWJVWjBXbFJ3VkdWWVRqQmFWekIxVlROU2VXRlhOVzVQYkVwWVRWaENhbVZVVmtSWGJHTXhZVzFHU0UxWGFHcGlXRkkyVkVWT1ExWXhjRmxUYm5Cb1ZucHNNVlZHVWtaa1ZURkVUa2hrVFdGclJucFRWVlpQVFZkS1NWVnFSbXBpVmxVMVdXMHhWMDFYVWtsVGJXaHBVVE5rYmxaVmFGZGhWMHBJWWtkd1ZFMXNXVEZXYTJNMVkyeHdXRTVFYkdsaWJGcDZXV3RGT1ZCUmNFUmlSMFo2WXpGU05XTkhWazlaVnpGc1QyeE9OV016VW14aVV6VlVaRWhLY0dKdFl6WlZiR040WTBkT05VNVZUbUZXZWxaeFdWVmplR0ZIVG5Sa1NIQk5ZVEJ3YzFsdE1VOWlNa3BZVW01c2FFMHdNVEZWYWtwWFRVWldTRkpxUW1oV01Wb3hXa1ZhUzJKR2EzbFBXR3hoVVZRd09RPT0KVGVzdE1ldGhvZEFyZ3VtZW50czpTeXN0ZW0uT2JqZWN0W106Uld4bGJXVnVkRlI1Y0dVNlUzbHpkR1Z0TGxOMGNtbHVaenBWTTJ4NlpFZFdkRXhyT1dsaGJWWnFaRUU5UFFwU1lXNXJPbE41YzNSbGJTNUpiblF6TWpveENsUnZkR0ZzVEdWdVozUm9PbE41YzNSbGJTNUpiblF6TWpveENreGxibWQwYURBNlUzbHpkR1Z0TGtsdWRETXlPakVLVEc5M1pYSkNiM1Z1WkRBNlUzbHpkR1Z0TGtsdWRETXlPakFLU1hSbGJUQTZVM2x6ZEdWdExrbHVkRE15T2pFd09EYzMKRGVmYXVsdE1ldGhvZERpc3BsYXk6U3lzdGVtLlN0cmluZzpRMnhoYzNOQmJtUk5aWFJvYjJRPQpEaXNjb3ZlckFyZ3VtZW50czpTeXN0ZW0uQm9vbGVhbjpGYWxzZQ=='
    Parameter name: serializedValue
       at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue)
       at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value)
       at Xunit.Sdk.TestCaseBulkDeserializer.Deserialize(ITestFrameworkDiscoverer discoverer,     ITestFrameworkExecutor executor, String serialization)
    [22/01/2018 16:00:30 Informational] [xUnit.net 00:00:00.3628375]   Starting:    Emis.Benchmarks
    [22/01/2018 16:00:31 Informational] [xUnit.net 00:00:00.4480046]   Finished:    Emis.Benchmarks
    [22/01/2018 16:00:31 Informational] ========== Run test finished: 0 run (0:00:00.8252824)     ==========

**Comment by jorive** [comment]
@alexanderkozlenko sorry, I have not spent more time on this issue as I was out of office last week.

**Comment by marcin-kowal** [comment]
Try downgrade xunit package to version: 2.3.0-beta5-build3769

**Comment by alexanderkozlenko** [comment]
https://github.com/dotnet/corefx/issues/30734
