### ISSUE TITLE
System.Runtime.InteropServices.COMException: 'The WMI data block or event notification has already been enabled. (Exception from HRESULT: 0x8007106E)'

### ISSUE THREAD

**Issue by jzabroski** [microsoft/xunit-performance#274]
```
System.Runtime.InteropServices.COMException: 'The WMI data block or event notification has already been enabled. (Exception from HRESULT: 0x8007106E)'
```

**Comment by jzabroski** [comment]
```
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventProfileSources.Set(Int32[] profileSourceIDs, Int32[] profileSourceIntervals)
   at Microsoft.Xunit.Performance.Api.ETWProfiler.SetPreciseMachineCounters(IEnumerable`1 providers)
   at Microsoft.Xunit.Performance.Api.ETWProfiler.Record(XUnitPerformanceSessionData xUnitPerformanceSessionData, XUnitPerformanceMetricData xUnitPerformanceMetricData, Action action)
   at Microsoft.Xunit.Performance.Api.XunitPerformanceHarness.RunBenchmarks(String assemblyFileName)
   at JohnZabroski.Xunit.Performance.Runner.Program.Main(String[] args) in D:\Source\JohnZabroski.Xunit.Performance.Runner\Program.cs:line 21
```

**Comment by aburakab** [comment]
I have something similar
```
Unhandled Exception: System.Runtime.InteropServices.COMException: The WMI data block or event notification has already been enabled. (Exception from HRESULT: 0x8007106E)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventProfileSources.Set(Int32[] profileSourceIDs, Int32[] profileSourceIntervals)
   at BenchmarkDotNet.Diagnostics.Windows.HardwareCounters.Enable(IEnumerable`1 counters)
   at BenchmarkDotNet.Diagnostics.Windows.PmcDiagnoser.GetInitializedStats(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnostics.Windows.EtwDiagnoser`1.Start(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnostics.Windows.PmcDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
   at BenchmarkDotNet.Toolchains.Executor.Execute(Process process, BenchmarkCase benchmarkCase, SynchronousProcessOutputLoggerWithDiagnoser loggerWithDiagnoser, ILogger logger)
```

**Comment by jzabroski** [comment]
@aburakab That's benchmarkdotnet. This issue is for xunit-performance, a now legacy technology. I actually filed a parallel issue in BenchmarkDotNet for this, and created what I believe to be the fix.

However, the immediate workaround for your problem is to force release your data collector sets.

**Comment by brianrob** [comment]
Closing prior to archive.
