### ISSUE TITLE
Insuffcient System resources when running tests concurrently

### ISSUE THREAD

**Issue by ianhays** [Microsoft/xunit-performance#92]
For CoreFX, when running build.cmd we run the tests concurrently. With the current perf runner (build 22), we run Corerun regardless of any test discovery results. This has the effect that ETW tracing is started for a number of csproj that don't actually have any perf tests associated with them. This is generally not an issue, but occasionally I'll get an error like this:
```
 xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

EXEC : warning : Insufficient system resources exist to complete the requested service. (Exception from HRESULT: 0x800705AA) [D:\git\
corefx\src\System.IO.FileSystem.Primitives\tests\System.IO.FileSystem.Primitives.Tests.csproj]
     at Microsoft.ProcessDomain.ProcDomain.<ExecuteAsync>d__26`1.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.Xunit.Performance.ETWLogging.<StartAsync>d__4.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.Xunit.Performance.EtwPerformanceMetricLogger.StartLogging(ProcessStartInfo runnerStartInfo)
     at Microsoft.Xunit.Performance.ProgramCore.RunTests(XunitPerformanceProject project)
     at Microsoft.Xunit.Performance.ProgramCore.Run(String[] args)
``` 

I don't come upon this issue when building and running the tests on a project-by-project basis.

**Comment by ericeil** [comment]
I think we should consider adding a global Mutex that prevents multiple simultaneous perf runs / ETW logging sessions.  However, for clean perf results you should be running these tests when nothing else of consequence is happening on the machine.  The analysis I'm working on should help somewhat with noise introduced by other processes competing for system resources, but it will still be important to try to run perf tests on a "quiet" machine.

**Comment by ericeil** [comment]
Thinking about my Mutex idea some more, I think this is probably unnecessary complexity that will only help sometimes.  It's really up to the user to run perf tests in a reasonably "quiet" environment.
